Repository BC-MAY-21-RN/kata-05-reservacion-de-vuelos-k05-t01, pull requests merged in 2021-07, with the labels that each got.

#7 Sign up form with Formik and Yup for validation
  FlightReservation/App.js
  FlightReservation/android/app/build.gradle
  FlightReservation/package-lock.json
  FlightReservation/package.json
  FlightReservation/src/screens/SignUp.js
Labels: wip

#21 Feature#4 register form style
  FlightReservation/package-lock.json
  FlightReservation/package.json
  FlightReservation/src/components/form/PasswordField.js
  FlightReservation/src/components/form/TextField.js
  FlightReservation/src/consts/colors.js
  FlightReservation/src/consts/style.js
  FlightReservation/src/screens/SignUp.js
Labels: review required

#23 Navigation between Log in and Sign up forms.
  FlightReservation/App.js
  FlightReservation/package-lock.json
  FlightReservation/src/screens/LogIn.js
  FlightReservation/src/screens/SignUp.js
Labels: mentor review required

#24 Validation Schema for Log In form added
  FlightReservation/src/schemas/logInSchema.js
  FlightReservation/src/screens/LogIn.js
Labels: mentor review required
